### ISSUE TITLE
can't install plugin into kong

### ISSUE THREAD

**Issue by ebratb** [Moesif/kong-plugin-moesif#1]
Installing 'kong-plugin-moesif' in a Kong docker container, luarocks can't find the plugin 'kong-plugin-moesif'

Running the following command:
`USER=root luarocks install kong-plugin-moesif`

One will get the following error:
`Error: No results matching query were found.`

**How to reproduce it:**
Run a shell instance on a kong's container:
`docker run --rm -it kong:0.14.1 sh`
once inside the shell in the running container, type:
`USER=root luarocks install kong-plugin-moesif`

Here, a Dockerfile to reporoduce the error:
[Dockerfile](https://github.com/Moesif/kong-plugin-moesif/files/2573310/Dockerfile.txt)

**Comment by keyur9** [comment]
Hello @ebratb Thanks for letting us know.

Running the following command will install the plugin in a Kong docker container:
`USER=root luarocks install --server=http://luarocks.org/manifests/moesif kong-plugin-moesif`

Here, a Dockerfile to install the plugin:
[Dockerfile](https://github.com/Moesif/kong-plugin-moesif/files/2573988/Dockerfile.txt)


Let us know if you're able to install the plugin.

**Comment by dgilling** [comment]
Hi @ebratb, did that fix your issue?

**Comment by dgilling** [comment]
Closing issue due to no response. Let us know if still experiencing a problem.
