### ISSUE TITLE
Lua warnings

### ISSUE THREAD

**Issue by mattburton** [Moesif/kong-plugin-moesif#14]
Trying out the Moesif Kong plugin - got up and running and was able to kick the tires a bit - looking pretty great so far. In trying to figure out an unrelated issue I was looking at the Kong logs and noticed the Moesif plugin was outputting a lot of warnings. Everything is working fine of course - these are just warnings from Lua, but in terms of reducing log noise I thought I'd pass them along - thanks!

Using Kong 1.4.0:
```
2019/10/31 15:25:12 [warn] 32#0: *123881 [lua] _G write guard:12: __newindex(): writing a global lua variable ('xForwardedFor') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
stack traceback:
        /usr/local/share/lua/5.1/kong/plugins/moesif/moesif_ser.lua:92: in function 'get_client_ip'
        /usr/local/share/lua/5.1/kong/plugins/moesif/moesif_ser.lua:222: in function 'serialize'
        /usr/local/share/lua/5.1/kong/plugins/moesif/handler.lua:75: in function </usr/local/share/lua/5.1/kong/plugins/moesif/handler.lua:73>
        /usr/local/share/lua/5.1/kong/init.lua:209: in function 'execute_plugins_iterator'
        /usr/local/share/lua/5.1/kong/init.lua:1068: in function 'log'
```
```
2019/10/31 15:25:15 [warn] 32#0: *128400 [lua] _G write guard:12: __newindex(): writing a global lua variable ('err') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
stack traceback:
        /usr/local/share/lua/5.1/kong/plugins/moesif/connection.lua:21: in function 'get_connection'
        /usr/local/share/lua/5.1/kong/plugins/moesif/log.lua:141: in function </usr/local/share/lua/5.1/kong/plugins/moesif/log.lua:130>, context: ngx.timer
```
```
2019/10/31 15:24:40 [warn] 32#0: *126573 [lua] _G write guard:12: __newindex(): writing a global lua variable ('err') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
stack traceback:
        /usr/local/share/lua/5.1/kong/plugins/moesif/log.lua:51: in function 'send_payload'
        /usr/local/share/lua/5.1/kong/plugins/moesif/log.lua:149: in function </usr/local/share/lua/5.1/kong/plugins/moesif/log.lua:130>, context: ngx.timer
```
```
2019/10/31 15:23:55 [warn] 32#0: *124200 [lua] _G write guard:12: __newindex(): writing a global lua variable ('err') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
stack traceback:
        /usr/local/share/lua/5.1/kong/plugins/moesif/log.lua:51: in function 'send_payload'
        /usr/local/share/lua/5.1/kong/plugins/moesif/log.lua:149: in function </usr/local/share/lua/5.1/kong/plugins/moesif/log.lua:130>, context: ngx.timer
```

**Comment by dgilling** [comment]
Thanks at @mattburton for letting us know. Agree we shouldn't be outputting so many. We'll add some options to only enable for debug. @keyur9

**Comment by mattburton** [comment]
@dgilling suppressing is one thing, but I believe these are actual warnings about global variables being updated by concurrent requests - I only just wrote my first Lua code the other day when working on a custom Kong plugin so I'm no expert by any means, but I hit the same issue pretty quickly - I think for the first example at least it would be fixed by adding `local` in front of `xForwardedFor`. The rest are just a matter of making sure that you're not trying to use a global `err` but rather one scoped to your current function, etc... Might make for a nasty bug if concurrent requests are altering each other's state.

**Comment by dgilling** [comment]
Hi @mattburton. Thanks for letting us know! We pushed out a new version on Luarocks 0.2.0. Let me know if that fixes you're issues.

**Comment by mattburton** [comment]
@dgilling thanks! looking pretty good so far, only getting one warning now in the logs:
```
2019/11/01 18:35:30 [warn] 32#0: *1232 [lua] _G write guard:12: __newindex(): writing a global lua variable ('transaction_id') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
stack traceback:
        /usr/local/share/lua/5.1/kong/plugins/moesif/handler.lua:40: in function </usr/local/share/lua/5.1/kong/plugins/moesif/handler.lua:26>
```

**Comment by dgilling** [comment]
@mattburton Thanks for letting me know. We pushed one more fix 0.2.1 that fixes this.

**Comment by mattburton** [comment]
@dgilling the warnings are gone, but unfortunately now it doesn't seem that requests are showing up in Moesif - I might get one here and there to show up, so it's not entirely broken, so I'm not sure what's causing it. I changed my queue size in the plugin to 1 to try to force it to send each individual request to no avail. I did notice that my application ID seems to be changing daily, which I assume is done during a trial, so I've been keeping that up to date as well.

**Comment by dgilling** [comment]
I see. Sorry about that. We’ll recheck the release. Sounds like the version
before still worked (0.1.0)?  Regarding the app Id, it’s ok if it changes,
the old one is still valid. The token is a JWT that encodes the key
creation day.

Derric
