### ISSUE TITLE
kong doesn't start when I install the plugin: moesif_ser.lua:5: attempt to index field 'resp' (a nil value)

### ISSUE THREAD

**Issue by anto-progetica** [Moesif/kong-plugin-moesif#99]
Tested on: Kong ingress controller with helm

repository: kong
tag: "3.5"

repository: kong/kubernetes-ingress-controller
tag: "3.0"

Hi,
i ran the guide to setup the moesif plugin inside a k8s cluster via ingress-ontroller using helm. When I launch the helm upgrade command, as described in the instructions, the pod fails during startup. Looking at the logs I find the following errors:

`
2024/03/13 15:34:49 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:786: error loading module 'kong.plugins.moesif.handler':
/opt/kong/plugins/moesif/moesif_ser.lua:5: attempt to index field 'resp' (a nil value)
stack traceback:
        /opt/kong/plugins/moesif/moesif_ser.lua:5: in main chunk
        [C]: in function 'require'
        /opt/kong/plugins/moesif/handler.lua:1: in main chunk
        [C]: at 0x7f3deeb99610
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/tools/utils.lua:777: in function 'load_module_if_exists'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:154: in function 'load_plugin_handler'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:260: in function 'load_plugin'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:312: in function 'load_plugin_schemas'
        /usr/local/share/lua/5.1/kong/init.lua:695: in function 'init'
        init_by_lua:23: in main chunk
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/tools/utils.lua:786: in function 'load_module_if_exists'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:154: in function 'load_plugin_handler'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:260: in function 'load_plugin'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:312: in function 'load_plugin_schemas'
        /usr/local/share/lua/5.1/kong/init.lua:695: in function 'init'
        init_by_lua:23: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:786: error loading module 'kong.plugins.moesif.handler':   
/opt/kong/plugins/moesif/moesif_ser.lua:5: attempt to index field 'resp' (a nil value)
stack traceback:
        /opt/kong/plugins/moesif/moesif_ser.lua:5: in main chunk
        [C]: in function 'require'
        /opt/kong/plugins/moesif/handler.lua:1: in main chunk
        [C]: at 0x7f3deeb99610
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/tools/utils.lua:777: in function 'load_module_if_exists'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:154: in function 'load_plugin_handler'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:260: in function 'load_plugin'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:312: in function 'load_plugin_schemas'
        /usr/local/share/lua/5.1/kong/init.lua:695: in function 'init'
        init_by_lua:23: in main chunk
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/tools/utils.lua:786: in function 'load_module_if_exists'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:154: in function 'load_plugin_handler'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:260: in function 'load_plugin'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:312: in function 'load_plugin_schemas'
        /usr/local/share/lua/5.1/kong/init.lua:695: in function 'init'
        init_by_lua:23: in main chunk
`
The issue occurs because for some reason a resp is nil. I replaced the line with an if that evaluates this condition and then the pod started.

`local res_get_headers = ngx.resp and ngx.resp.get_headers or nil`

**Comment by praves77** [comment]
Thanks @anto-progetica - much appreciated reporting of the issue in details. We will review it and release a fix asap. (internal ticket #187231825)

**Comment by praves77** [comment]
Hello @anto-progetica . We've published new version `2.0.11` with the fix. Thanks for the patience.

**Comment by praves77** [comment]
Resolved by PR #100

**Comment by anto-progetica** [comment]
Thank you
